import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import localFont from 'next/font/local';
import "./globals.css";
import AllProvider from "./store/all";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = localFont({
  src: './fonts/Roboto-Regular.ttf',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // ✅ Add the roboto.className here to apply the font
        className={`${roboto.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AllProvider>
          <Toaster position="top-center" reverseOrder={false} />
          {children}
        </AllProvider>
      </body>
    </html>
  );
}